version: '3.4'
services:
  basketdb:
    image: redis:latest   
    container_name: basketdb
    restart: always
    ports:
       - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
       -  redis-data:/data
  
  redis-commander:
    image: rediscommander/redis-commander  
    container_name: redis-commander
    restart: always
    environment:
      - REDIS_HOSTS=local:basketdb:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - basketdb


volumes:
  redis-data: